/**
 * Response status codes.
 */
const statusCodes = {
	STATUS_OK: 200,
	STATUS_BAD_REQUEST: 400,
	STATUS_UNAUTHROIZED: 401,
	STATUS_FORBIDDEN: 403,
	STATUS_NOT_FOUND: 404,
	STATUS_SERVER_ERROR: 500,
	STATUS_UNPROCESSABLE_ENTITY: 422,
}

export default statusCodes;